// <auto-generated />
using System;
using CostaRica.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CostaRica.Api.Data.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    partial class DirectoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BusinessPageGoogleCategory", b =>
                {
                    b.Property<Guid>("BusinessPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoogleCategoriesId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessPageId", "GoogleCategoriesId");

                    b.HasIndex("GoogleCategoriesId");

                    b.ToTable("BusinessGoogleCategories", (string)null);
                });

            modelBuilder.Entity("BusinessPageMediaAsset", b =>
                {
                    b.Property<Guid>("BusinessPagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessPagesId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("BusinessMedia", (string)null);
                });

            modelBuilder.Entity("BusinessPageTag", b =>
                {
                    b.Property<Guid>("BusinessPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessPageId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BusinessTags", (string)null);
                });

            modelBuilder.Entity("CostaRica.Api.Data.BusinessPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BusinessPages");
                });

            modelBuilder.Entity("CostaRica.Api.Data.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Point>("Center")
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CostaRica.Api.Data.GoogleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Gcid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GoogleCategories");
                });

            modelBuilder.Entity("CostaRica.Api.Data.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltTextEn")
                        .HasColumnType("text");

                    b.Property<string>("AltTextEs")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TagGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TagGroupId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CostaRica.Api.Data.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TagGroups");
                });

            modelBuilder.Entity("BusinessPageGoogleCategory", b =>
                {
                    b.HasOne("CostaRica.Api.Data.BusinessPage", null)
                        .WithMany()
                        .HasForeignKey("BusinessPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.GoogleCategory", null)
                        .WithMany()
                        .HasForeignKey("GoogleCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessPageMediaAsset", b =>
                {
                    b.HasOne("CostaRica.Api.Data.BusinessPage", null)
                        .WithMany()
                        .HasForeignKey("BusinessPagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessPageTag", b =>
                {
                    b.HasOne("CostaRica.Api.Data.BusinessPage", null)
                        .WithMany()
                        .HasForeignKey("BusinessPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CostaRica.Api.Data.BusinessPage", b =>
                {
                    b.HasOne("CostaRica.Api.Data.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("CostaRica.Api.Data.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CostaRica.Api.Data.BusinessContacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("BusinessPageId");

                            b1.Property<string>("Facebook");

                            b1.Property<string>("Instagram");

                            b1.Property<string>("OwnerName");

                            b1.Property<long?>("PhoneCallable");

                            b1.Property<long?>("PhoneWhatsapp");

                            b1.HasKey("BusinessPageId");

                            b1.ToTable("BusinessPages");

                            b1
                                .ToJson("Contacts")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPageId");
                        });

                    b.OwnsOne("CostaRica.Api.Data.BusinessSeoSettings", "Seo", b1 =>
                        {
                            b1.Property<Guid>("BusinessPageId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("Description");

                            b1.Property<string>("Keywords");

                            b1.Property<bool>("NoFollow");

                            b1.Property<bool>("NoIndex");

                            b1.Property<string>("OgDescription");

                            b1.Property<Guid?>("OgImageId");

                            b1.Property<string>("OgTitle");

                            b1.Property<string>("OgType");

                            b1.Property<string>("PriceRange");

                            b1.Property<string>("SchemaType");

                            b1.Property<string>("Title");

                            b1.HasKey("BusinessPageId");

                            b1.ToTable("BusinessPages");

                            b1
                                .ToJson("Seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPageId");

                            b1.OwnsMany("CostaRica.Api.Data.ManualHreflang", "Hreflangs", b2 =>
                                {
                                    b2.Property<Guid>("BusinessSeoSettingsBusinessPageId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("LangCode")
                                        .IsRequired();

                                    b2.Property<string>("Url")
                                        .IsRequired();

                                    b2.HasKey("BusinessSeoSettingsBusinessPageId", "__synthesizedOrdinal");

                                    b2.ToTable("BusinessPages");

                                    b2.WithOwner()
                                        .HasForeignKey("BusinessSeoSettingsBusinessPageId");
                                });

                            b1.Navigation("Hreflangs");
                        });

                    b.OwnsMany("CostaRica.Api.Data.ScheduleDay", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("BusinessPageId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("Days")
                                .IsRequired();

                            b1.HasKey("BusinessPageId", "__synthesizedOrdinal");

                            b1.ToTable("BusinessPages");

                            b1
                                .ToJson("Schedule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPageId");

                            b1.OwnsMany("CostaRica.Api.Data.ScheduleInterval", "Intervals", b2 =>
                                {
                                    b2.Property<Guid>("ScheduleDayBusinessPageId");

                                    b2.Property<int>("ScheduleDay__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("End")
                                        .IsRequired();

                                    b2.Property<int>("EndMinutes");

                                    b2.Property<string>("Start")
                                        .IsRequired();

                                    b2.Property<int>("StartMinutes");

                                    b2.HasKey("ScheduleDayBusinessPageId", "ScheduleDay__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("BusinessPages");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduleDayBusinessPageId", "ScheduleDay__synthesizedOrdinal");
                                });

                            b1.Navigation("Intervals");
                        });

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("Province");

                    b.Navigation("Schedule");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("CostaRica.Api.Data.City", b =>
                {
                    b.HasOne("CostaRica.Api.Data.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Tag", b =>
                {
                    b.HasOne("CostaRica.Api.Data.TagGroup", "TagGroup")
                        .WithMany()
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TagGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
