@base_url = http://localhost:5046/api
@contentType = application/json

### 1. АВТОРИЗАЦИЯ
# @name loginAdmin
POST {{base_url}}/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "ComplexPassword123!"
}

###
@token = {{loginAdmin.response.body.$.token}}


### 2. СОЗДАНИЕ ТЕСТОВЫХ ДАННЫХ (SEEDING)

# 2.1. Загрузка первого ассета (POST на корень ресурса)
# @name createOrphan
POST {{base_url}}/media
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="slug"

orphan-asset-{{$guid}}
--WebAppBoundary
Content-Disposition: form-data; name="altTextEn"

Orphan Image Description
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test1.png"
Content-Type: image/png

< ./test_input.png
--WebAppBoundary--

###
@orphanId = {{createOrphan.response.body.$.id}}

# 2.2. Загрузка второго ассета
# @name createLinked
POST {{base_url}}/media
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="slug"

linked-asset-{{$guid}}
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test2.png"
Content-Type: image/png

< ./test_input.png
--WebAppBoundary--

###
@linkedId = {{createLinked.response.body.$.id}}


### 3. ПОЛУЧЕНИЕ И ФИЛЬТРАЦИЯ (READ)

# 3.1. Список с сортировкой и пагинацией
GET {{base_url}}/media?sort=["slug","ASC"]&range=[0,9]
Authorization: Bearer {{token}}

###

# 3.2. Проверка фильтра "СИРОТЫ"
GET {{base_url}}/media?filter={"onlyOrphans":true}
Authorization: Bearer {{token}}

###

# 3.3. Глобальный поиск по части слага
GET {{base_url}}/media?filter={"q":"linked-asset"}
Authorization: Bearer {{token}}


### 4. ТЕСТ КОНФЛИКТА УДАЛЕНИЯ (409 CONFLICT)

# 4.1. Попытка удаления ассета (в системе уже должны быть связи)
# Если ассет привязан в БД, этот запрос вернет 409
DELETE {{base_url}}/media/{{linkedId}}
Authorization: Bearer {{token}}


### 5. ОЧИСТКА (DELETE)

# 5.1. Успешное удаление "сироты"
DELETE {{base_url}}/media/{{orphanId}}
Authorization: Bearer {{token}}

###

# 5.2. Тест ошибки: Загрузка без Slug (должен вернуть 400 Bad Request)
POST {{base_url}}/media
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="fail.png"
Content-Type: image/png

< ./test_input.png
--WebAppBoundary--