@base_url = http://localhost:5046
@contentType = application/json

############################################################
### 1. АВТОРИЗАЦИЯ (SUPER ADMIN)
############################################################

# @name loginAdmin
POST {{base_url}}/api/auth/login
Content-Type: {{contentType}}

{
  "email": "admin@example.com",
  "password": "ComplexPassword123!"
}

###
@token = {{loginAdmin.response.body.$.token}}


############################################################
### 2. ПОДГОТОВКА ДАННЫХ (Прoвинции и Города)
############################################################

### 2.1 Создаем Провинцию А (будет с городами)
# @name createProvA
POST {{base_url}}/api/provinces
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{ 
  "name": "Test-Prov-A-{{$guid}}", 
  "slug": "slug-a-{{$guid}}" 
}

###
@idProvA = {{createProvA.response.body.$.id}}

### 2.2 Создаем Город в Провинции А (создаем зависимость)
POST {{base_url}}/api/cities
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "name": "City-In-A-{{$guid}}",
  "slug": "city-a-{{$guid}}",
  "provinceId": "{{idProvA}}"
}

### 2.3 Создаем Провинцию B (будет пустая)
# @name createProvB
POST {{base_url}}/api/provinces
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{ 
  "name": "Test-Prov-B-{{$guid}}", 
  "slug": "slug-b-{{$guid}}" 
}

###
@idProvB = {{createProvB.response.body.$.id}}


############################################################
### 3. ТЕСТ ЗАЩИЩЕННОГО УДАЛЕНИЯ
############################################################

### 3.1 ПРОВЕРКА КОНФЛИКТА (Удаление Провинции А)
# Ожидаемый результат: 409 Conflict
# Тело ответа должно содержать детальную ошибку о наличии городов.
DELETE {{base_url}}/api/provinces/{{idProvA}}
Authorization: Bearer {{token}}


### 3.2 ПРОВЕРКА УСПЕХА (Удаление Провинции B)
# Ожидаемый результат: 204 No Content
# Провинция пустая, удаление должно пройти мгновенно.
DELETE {{base_url}}/api/provinces/{{idProvB}}
Authorization: Bearer {{token}}


############################################################
### 4. ПРОВЕРКА ПОИСКА (УБЕДИТЬСЯ ЧТО ДАННЫЕ В БАЗЕ)
############################################################

### 4.1 Поиск созданной Провинции А по части имени
# Должна вернуться одна запись (Провинция А), так как B уже удалена.
GET {{base_url}}/api/provinces?filter={"Q":"Test-Prov-A"}
Authorization: Bearer {{token}}