// <auto-generated />
using System;
using CostaRica.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CostaRica.Api.Migrations
{
    [DbContext(typeof(DirectoryDbContext))]
    [Migration("20260325000000_AddIdentity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // ── JOIN TABLES (Many-to-Many) ────────────────────────────────────────

            modelBuilder.Entity("BusinessPageGoogleCategory", b =>
                {
                    b.Property<Guid>("BusinessPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SecondaryCategoriesId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessPageId", "SecondaryCategoriesId");

                    b.HasIndex("SecondaryCategoriesId");

                    b.ToTable("BusinessSecondaryCategories", (string)null);
                });

            modelBuilder.Entity("BusinessPageMediaAsset", b =>
                {
                    b.Property<Guid>("BusinessPagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MediaId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessPagesId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("BusinessMedia", (string)null);
                });

            modelBuilder.Entity("BusinessPageTag", b =>
                {
                    b.Property<Guid>("BusinessPageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("BusinessPageId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BusinessTags", (string)null);
                });

            // ── IDENTITY ENTITIES ─────────────────────────────────────────────────

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CostaRica.Api.Data.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            // ── DOMAIN ENTITIES ───────────────────────────────────────────────────

            modelBuilder.Entity("CostaRica.Api.Data.BusinessPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography(Point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("OldSlugs")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<Guid?>("PrimaryCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("OldSlugs");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("OldSlugs"), "gin");

                    b.HasIndex("PrimaryCategoryId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("BusinessPages");
                });

            modelBuilder.Entity("CostaRica.Api.Data.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("CostaRica.Api.Data.GoogleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Gcid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GoogleCategories");
                });

            modelBuilder.Entity("CostaRica.Api.Data.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltTextEn")
                        .HasColumnType("text");

                    b.Property<string>("AltTextEs")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TagGroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TagGroupId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("CostaRica.Api.Data.TagGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameEs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("TagGroups");
                });

            // ── RELATIONSHIPS: IDENTITY ───────────────────────────────────────────

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("CostaRica.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("CostaRica.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("CostaRica.Api.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            // ── RELATIONSHIPS: DOMAIN ─────────────────────────────────────────────

            modelBuilder.Entity("BusinessPageGoogleCategory", b =>
                {
                    b.HasOne("CostaRica.Api.Data.BusinessPage", null)
                        .WithMany()
                        .HasForeignKey("BusinessPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.GoogleCategory", null)
                        .WithMany()
                        .HasForeignKey("SecondaryCategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessPageMediaAsset", b =>
                {
                    b.HasOne("CostaRica.Api.Data.BusinessPage", null)
                        .WithMany()
                        .HasForeignKey("BusinessPagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.MediaAsset", null)
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessPageTag", b =>
                {
                    b.HasOne("CostaRica.Api.Data.BusinessPage", null)
                        .WithMany()
                        .HasForeignKey("BusinessPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CostaRica.Api.Data.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CostaRica.Api.Data.BusinessPage", b =>
                {
                    b.HasOne("CostaRica.Api.Data.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostaRica.Api.Data.GoogleCategory", "PrimaryCategory")
                        .WithMany()
                        .HasForeignKey("PrimaryCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CostaRica.Api.Data.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("CostaRica.Api.Data.BusinessContacts", "Contacts", b1 =>
                        {
                            b1.Property<Guid>("BusinessPageId");

                            b1.Property<string>("Facebook");

                            b1.Property<string>("Instagram");

                            b1.Property<string>("OwnerName");

                            b1.Property<long?>("PhoneCallable");

                            b1.Property<long?>("PhoneWhatsapp");

                            b1.HasKey("BusinessPageId");

                            b1.ToTable("BusinessPages");

                            b1
                                .ToJson("Contacts")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPageId");
                        });

                    b.OwnsOne("CostaRica.Api.Data.BusinessSeoSettings", "Seo", b1 =>
                        {
                            b1.Property<Guid>("BusinessPageId");

                            b1.Property<string>("CanonicalUrl");

                            b1.Property<string>("Description");

                            b1.Property<string>("Keywords");

                            b1.Property<bool>("NoFollow");

                            b1.Property<bool>("NoIndex");

                            b1.Property<string>("OgDescription");

                            b1.Property<Guid?>("OgImageId");

                            b1.Property<string>("OgTitle");

                            b1.Property<string>("OgType");

                            b1.Property<string>("PriceRange");

                            b1.Property<string>("SchemaType");

                            b1.Property<string>("Title");

                            b1.HasKey("BusinessPageId");

                            b1.ToTable("BusinessPages");

                            b1
                                .ToJson("Seo")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPageId");

                            b1.OwnsMany("CostaRica.Api.Data.ManualHreflang", "Hreflangs", b2 =>
                                {
                                    b2.Property<Guid>("BusinessSeoSettingsBusinessPageId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("LangCode")
                                        .IsRequired();

                                    b2.Property<string>("Url")
                                        .IsRequired();

                                    b2.HasKey("BusinessSeoSettingsBusinessPageId", "__synthesizedOrdinal");

                                    b2.ToTable("BusinessPages");

                                    b2.WithOwner()
                                        .HasForeignKey("BusinessSeoSettingsBusinessPageId");
                                });

                            b1.Navigation("Hreflangs");
                        });

                    b.OwnsMany("CostaRica.Api.Data.ScheduleDay", "Schedule", b1 =>
                        {
                            b1.Property<Guid>("BusinessPageId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("Days")
                                .IsRequired();

                            b1.HasKey("BusinessPageId", "__synthesizedOrdinal");

                            b1.ToTable("BusinessPages");

                            b1
                                .ToJson("Schedule")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPageId");

                            b1.OwnsMany("CostaRica.Api.Data.ScheduleInterval", "Intervals", b2 =>
                                {
                                    b2.Property<Guid>("ScheduleDayBusinessPageId");

                                    b2.Property<int>("ScheduleDay__synthesizedOrdinal");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("End")
                                        .IsRequired();

                                    b2.Property<int>("EndMinutes");

                                    b2.Property<string>("Start")
                                        .IsRequired();

                                    b2.Property<int>("StartMinutes");

                                    b2.HasKey("ScheduleDayBusinessPageId", "ScheduleDay__synthesizedOrdinal", "__synthesizedOrdinal");

                                    b2.ToTable("BusinessPages");

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduleDayBusinessPageId", "ScheduleDay__synthesizedOrdinal");
                                });

                            b1.Navigation("Intervals");
                        });

                    b.Navigation("City");

                    b.Navigation("Contacts")
                        .IsRequired();

                    b.Navigation("PrimaryCategory");

                    b.Navigation("Province");

                    b.Navigation("Schedule");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("CostaRica.Api.Data.City", b =>
                {
                    b.HasOne("CostaRica.Api.Data.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Tag", b =>
                {
                    b.HasOne("CostaRica.Api.Data.TagGroup", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("CostaRica.Api.Data.Province", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("CostaRica.Api.Data.TagGroup", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
